const drumBeats = {
    "2/4": "dd 76 77 60 30",
    "3/4": "ddd 76 77 77 60 30 30",
    "4/4": "dddd 76 77 77 77 60 30 30 30",
    "5/4": "ddddd 76 77 77 76 77 60 30 30 60 30",
    "2/2": "dd 76 77 60 30",
    "6/8": "dddddd 76 77 77 76 77 77 60 30 30 50 30 30",
    "9/8": "ddd 76 77 77 60 30 30",
    "12/8": "dddd 76 77 77 77 60 30 30 30"
};

interface pitchName {
    note:string
    oct:string
    abc:string
}
const pitchNames = {
    21:{note: "A", oct: "Субконтроктава", abc: "A,,,,"},
    22:{note: "B♭", oct: "Субконтроктава", abc: "_B,,,,"},
    23:{note: "B", oct: "Субконтроктава", abc: "B,,,,"},
    24:{note: "C", oct: "Контроктава", abc: "C,,,"},
    25:{note: "C#", oct: "Контроктава", abc: "^C,,,"},
    26:{note: "D", oct: "Контроктава", abc: "D,,,"},
    27:{note: "E♭", oct: "Контроктава", abc: "_E,,,"},
    28:{note: "E", oct: "Контроктава", abc: "E,,,"},
    29:{note: "F", oct: "Контроктава", abc: "F,,,"},
    30:{note: "F#", oct: "Контроктава", abc: "^F,,,"},
    31:{note: "G", oct: "Контроктава", abc: "G,,,"},
    32:{note: "A♭", oct: "Контроктава", abc: "_A,,,"},
    33:{note: "A", oct: "Контроктава", abc: "A,,,"},
    34:{note: "A#", oct: "Контроктава", abc: "_B,,,"},
    35:{note: "B", oct: "Контроктава", abc: "B,,,"},
    36:{note: "C", oct: "Большая", abc: "C,,"},
    37:{note: "C#", oct: "Большая", abc: "^C,,"},
    38:{note: "D", oct: "Большая", abc: "D,,"},
    39:{note: "E♭", oct: "Большая", abc: "_E,,"},
    40:{note: "E", oct: "Большая", abc: "E,,"},
    41:{note: "F", oct: "Большая", abc: "F,,"},
    42:{note: "F#", oct: "Большая", abc: "^F,,"},
    43:{note: "G", oct: "Большая", abc: "G,,"},
    44:{note: "A♭", oct: "Большая", abc: "_A,,"},
    45:{note: "A", oct: "Большая", abc: "A,,"},
    46:{note: "B♭", oct: "Большая", abc: "_B,,"},
    47:{note: "B", oct: "Большая", abc: "B,,"},
    48:{note: "C", oct: "Малая", abc: "C,"},
    49:{note: "C#", oct: "Малая", abc: "^C,"},
    50:{note: "D", oct: "Малая", abc: "D,"},
    51:{note: "E♭", oct: "Малая", abc: "_E,"},
    52:{note: "E", oct: "Малая", abc: "E,"},
    53:{note: "F", oct: "Малая", abc: "F,"},
    54:{note: "F#", oct: "Малая", abc: "^F,"},
    55:{note: "G", oct: "Малая", abc: "G,"},
    56:{note: "A♭", oct: "Малая", abc: "_A,"},
    57:{note: "A", oct: "Малая", abc: "A,"},
    58:{note: "B♭", oct: "Малая", abc: "_B,"},
    59:{note: "B", oct: "Малая", abc: "B,"},
    60:{note: "C", oct: "Первая", abc: "C"},
    61:{note: "C#", oct: "Первая", abc: "^C"},
    62:{note: "D", oct: "Первая", abc: "D"},
    63:{note: "E♭", oct: "Первая", abc: "_E"},
    64:{note: "E", oct: "Первая", abc: "E"},
    65:{note: "F", oct: "Первая", abc: "F"},
    66:{note: "F#", oct: "Первая", abc: "^F"},
    67:{note: "G", oct: "Первая", abc: "G"},
    68:{note: "A♭", oct: "Первая", abc: "_A"},
    69:{note: "A", oct: "Первая", abc: "A"},
    70:{note: "B♭", oct: "Первая", abc: "_B"},
    71:{note: "B", oct: "Первая", abc: "B"},
    72:{note: "C", oct: "Вторая", abc: "c"},
    73:{note: "C#", oct: "Вторая", abc: "^c"},
    74:{note: "D", oct: "Вторая", abc: "d"},
    75:{note: "E♭", oct: "Вторая", abc: "_e"},
    76:{note: "E", oct: "Вторая", abc: "e"},
    77:{note: "F", oct: "Вторая", abc: "f"},
    78:{note: "F#", oct: "Вторая", abc: "^f"},
    79:{note: "G", oct: "Вторая", abc: "g"},
    80:{note: "A♭", oct: "Вторая", abc: "_a"},
    81:{note: "A", oct: "Вторая", abc: "a"},
    82:{note: "B♭", oct: "Вторая", abc: "_b"},
    83:{note: "B", oct: "Вторая", abc: "b"},
    84:{note: "C", oct: "Третья", abc: "c'"},
    85:{note: "C#", oct: "Третья", abc: "^c'"},
    86:{note: "D", oct: "Третья", abc: "d'"},
    87:{note: "E♭", oct: "Третья", abc: "_e'"},
    88:{note: "E", oct: "Третья", abc: "e'"},
    89:{note: "F", oct: "Третья", abc: "f'"},
    90:{note: "F#", oct: "Третья", abc: "^f'"},
    91:{note: "G", oct: "Третья", abc: "g'"},
    92:{note: "A♭", oct: "Третья", abc: "_a'"},
    93:{note: "A", oct: "Третья", abc: "a'"},
    94:{note: "B♭", oct: "Третья", abc: "_b'"},
    95:{note: "B", oct: "Третья", abc: "b'"},
    96:{note: "C", oct: "Четвертая", abc: "c''"},
    97:{note: "C#", oct: "Четвертая", abc: "^c''"},
    98:{note: "D", oct: "Четвертая", abc: "d''"},
    99:{note: "E♭", oct: "Четвертая", abc: "_e''"},
    100:{note: "E", oct: "Четвертая", abc: "e''"},
    101:{note: "F", oct: "Четвертая", abc: "f''"},
    102:{note: "F#", oct: "Четвертая", abc: "^f''"},
    103:{note: "G", oct: "Четвертая", abc: "g''"},
    104:{note: "A♭", oct: "Четвертая", abc: "_a''"},
    105:{note: "A", oct: "Четвертая", abc: "a''"},
    106:{note: "B♭", oct: "Четвертая", abc: "_b''"},
    107:{note: "B", oct: "Четвертая", abc: "b''"},
    108:{note: "C", oct: "Пятая", abc: "c'''"}
};